/* Dalarwen 5G — offline service worker.
   Pre-caches the whole site so it runs with no internet (ironically, for Dalarwen).
   Bump CACHE when content changes to force an update on next online visit. */
var CACHE = "dalarwen-offline-v35";
var ASSETS = [
  "./",
  "404.html",
  "about-dalarwen.html",
  "above.html",
  "adventure.html",
  "apple-touch-icon.png",
  "arcade.html",
  "assets/alien.gif",
  "assets/bee-frequency.jpg",
  "assets/bee.gif",
  "assets/construction.gif",
  "assets/coventry-conductor.jpg",
  "assets/cube3d.gif",
  "assets/dalarwen-zoomed-out.jpg",
  "assets/dancer.gif",
  "assets/email.gif",
  "assets/fire_bar.gif",
  "assets/flame.gif",
  "assets/globe.gif",
  "assets/heart.gif",
  "assets/loading.gif",
  "assets/melonsis-lemon.jpg",
  "assets/newblink.gif",
  "assets/radiation.gif",
  "assets/sam-humber.jpg",
  "assets/signal_waves.gif",
  "assets/spin5g.gif",
  "assets/star.gif",
  "assets/stars.gif",
  "assets/tower.gif",
  "assistant/index.html",
  "beeb/beeb.css",
  "beeb/dalarwen.html",
  "beeb/index.html",
  "bees.html",
  "careers.html",
  "clifftop-caravans.html",
  "credits.html",
  "dark.css",
  "downloads.html",
  "downloads/merger-presentation.html",
  "drone.js",
  "faq.html",
  "favicon-32.png",
  "favicon.ico",
  "favicon.svg",
  "forum/index.html",
  "free-up-lewis.html",
  "game-art/win1.png",
  "game-art/win2.png",
  "game-art/win3.png",
  "game-art/win4.png",
  "game-art/win5.png",
  "gate.js",
  "gov/index.html",
  "grid/index.html",
  "guestbook.html",
  "hub/hub.css",
  "hub/index.html",
  "hub/issue-15.html",
  "hub/issues.html",
  "icon-192.png",
  "icon-512.png",
  "ideal-for-a-murder.html",
  "index.html",
  "infinite-walks.html",
  "isamsj.html",
  "jencorp.html",
  "keep-dalarwen-dark.html",
  "lewis.html",
  "manifest.webmanifest",
  "manifesto.html",
  "matrix.html",
  "men-of-harlech.html",
  "org-chart.html",
  "patwa.html",
  "radiation.html",
  "retro.css",
  "retro.js",
  "reviews/index.html",
  "ring/bees-invented-5g.html",
  "ring/big-candle.html",
  "ring/conservatory-weather.html",
  "ring/coventry.html",
  "ring/cube-told-me-so.html",
  "ring/educated-stupid.html",
  "ring/electric-sheep-paper.html",
  "ring/held-toward-belgium.html",
  "ring/hull.html",
  "ring/lewis-dot-mov.html",
  "ring/loo-standing-society.html",
  "ring/nans-wifi-guide.html",
  "ring/nazca-peru.html",
  "ring/norfolk-mythology.html",
  "ring/pyramids-5g.html",
  "ring/ramblers-lying.html",
  "ring/ring.js",
  "ring/rotisserie-nan.html",
  "ring/scouse-5g.html",
  "ring/silence-premium.html",
  "ring/spite-tower-13.html",
  "sam.html",
  "signal-test.html",
  "signalexchange/index.html",
  "sitemap.html",
  "static.html",
  "the-corridor.html",
  "the-cube.html",
  "the-division.html",
  "the-quiet.html",
  "towers.html",
  "tube/index.html",
  "tv-licence.html",
  "unwrapped/index.html",
  "webring.html",
  "wiki/band-b-talk.html",
  "wiki/band-b.html",
  "wiki/bees-talk.html",
  "wiki/bees.html",
  "wiki/belgium-talk.html",
  "wiki/belgium.html",
  "wiki/big-candle-talk.html",
  "wiki/big-candle.html",
  "wiki/black-shuck-talk.html",
  "wiki/black-shuck.html",
  "wiki/buzz-based-research-talk.html",
  "wiki/buzz-based-research.html",
  "wiki/clifftop-caravans-talk.html",
  "wiki/clifftop-caravans.html",
  "wiki/dalarwen-5g-grid-talk.html",
  "wiki/dalarwen-5g-grid.html",
  "wiki/dalarwen-talk.html",
  "wiki/dalarwen.html",
  "wiki/dam-wall-road-talk.html",
  "wiki/dam-wall-road.html",
  "wiki/detector-vans-talk.html",
  "wiki/detector-vans.html",
  "wiki/division-of-absence-talk.html",
  "wiki/division-of-absence.html",
  "wiki/electric-rain-talk.html",
  "wiki/electric-rain.html",
  "wiki/electric-sheep-paper-talk.html",
  "wiki/electric-sheep-paper.html",
  "wiki/electric-sheep-talk.html",
  "wiki/electric-sheep.html",
  "wiki/exclusion-envelope-talk.html",
  "wiki/exclusion-envelope.html",
  "wiki/four-hour-train-talk.html",
  "wiki/four-hour-train.html",
  "wiki/great-darkening-talk.html",
  "wiki/great-darkening.html",
  "wiki/hull-talk.html",
  "wiki/hull.html",
  "wiki/index.html",
  "wiki/infinite-walks-talk.html",
  "wiki/infinite-walks.html",
  "wiki/infinity-pitch-talk.html",
  "wiki/infinity-pitch.html",
  "wiki/isam-talk.html",
  "wiki/isam.html",
  "wiki/isamsj-talk.html",
  "wiki/isamsj.html",
  "wiki/jencorp-talk.html",
  "wiki/jencorp.html",
  "wiki/kb.js",
  "wiki/lantern-men-talk.html",
  "wiki/lantern-men.html",
  "wiki/lewis-talk.html",
  "wiki/lewis.html",
  "wiki/llandovery-talk.html",
  "wiki/llandovery.html",
  "wiki/llyn-brianne-talk.html",
  "wiki/llyn-brianne.html",
  "wiki/loo-standing-society-talk.html",
  "wiki/loo-standing-society.html",
  "wiki/melonsis-borealis-talk.html",
  "wiki/melonsis-borealis.html",
  "wiki/men-of-harlech-talk.html",
  "wiki/men-of-harlech.html",
  "wiki/nan-talk.html",
  "wiki/nan.html",
  "wiki/nazca-lines-talk.html",
  "wiki/nazca-lines.html",
  "wiki/neil-talk.html",
  "wiki/neil.html",
  "wiki/oat-milk-talk.html",
  "wiki/oat-milk.html",
  "wiki/offline-industrial-complex-talk.html",
  "wiki/offline-industrial-complex.html",
  "wiki/org-structure-talk.html",
  "wiki/org-structure.html",
  "wiki/project-dark-sky-talk.html",
  "wiki/project-dark-sky.html",
  "wiki/quad-void-talk.html",
  "wiki/quad-void.html",
  "wiki/red-kites-talk.html",
  "wiki/red-kites.html",
  "wiki/sam-talk.html",
  "wiki/sam.html",
  "wiki/sams-hectares-talk.html",
  "wiki/sams-hectares.html",
  "wiki/sedgley-holdings-talk.html",
  "wiki/sedgley-holdings.html",
  "wiki/sent-to-coventry-talk.html",
  "wiki/sent-to-coventry.html",
  "wiki/silence-premium-talk.html",
  "wiki/silence-premium.html",
  "wiki/storm-watching-talk.html",
  "wiki/storm-watching.html",
  "wiki/the-capstone-talk.html",
  "wiki/the-capstone.html",
  "wiki/the-conservatory-talk.html",
  "wiki/the-conservatory.html",
  "wiki/the-cube-talk.html",
  "wiki/the-cube.html",
  "wiki/the-firepit-talk.html",
  "wiki/the-firepit.html",
  "wiki/the-hill-talk.html",
  "wiki/the-hill.html",
  "wiki/the-pals-talk.html",
  "wiki/the-pals.html",
  "wiki/the-pyramids-talk.html",
  "wiki/the-pyramids.html",
  "wiki/the-quiet-talk.html",
  "wiki/the-quiet.html",
  "wiki/the-ramblers-talk.html",
  "wiki/the-ramblers.html",
  "wiki/the-spacesuit-talk.html",
  "wiki/the-spacesuit.html",
  "wiki/the-wormhole-talk.html",
  "wiki/the-wormhole.html",
  "wiki/tower-thirteen-talk.html",
  "wiki/tower-thirteen.html",
  "wiki/tv-licence-suppression-talk.html",
  "wiki/tv-licence-suppression.html",
  "wiki/wales-talk.html",
  "wiki/wales.html",
  "wiki/wiki.css",
  "wiki/zero-bars-talk.html",
  "wiki/zero-bars.html",
  "wiki/zombie-double-talk.html",
  "wiki/zombie-double.html",
  "work/index.html",
  "x/index.html"
];
self.addEventListener("install", function(e){
  self.skipWaiting();
  e.waitUntil(caches.open(CACHE).then(function(c){
    return Promise.all(ASSETS.map(function(u){
      return c.add(new Request(u, {cache:"reload"})).catch(function(){ });
    }));
  }));
});
self.addEventListener("activate", function(e){
  e.waitUntil(caches.keys().then(function(keys){
    return Promise.all(keys.map(function(k){ if(k!==CACHE) return caches.delete(k); }));
  }).then(function(){ return self.clients.claim(); }));
});
self.addEventListener("fetch", function(e){
  if(e.request.method!=="GET") return;
  var url=new URL(e.request.url);
  if(url.origin!==location.origin) return;
  // HTML documents: NETWORK-FIRST so pages are always fresh when online,
  // falling back to the cached copy only when offline. (Avoids serving stale pages.)
  var isDoc = e.request.mode==="navigate" || /\.html($|\?)/.test(url.pathname) || url.pathname.endsWith("/");
  if(isDoc){
    e.respondWith(
      fetch(e.request).then(function(net){
        try{ var copy=net.clone(); caches.open(CACHE).then(function(c){ c.put(e.request, copy); }); }catch(err){}
        return net;
      }).catch(function(){
        return caches.match(e.request, {ignoreSearch:true}).then(function(hit){
          return hit || caches.match("index.html", {ignoreSearch:true});
        });
      })
    );
    return;
  }
  // Assets (css/js/images/fonts): cache-first for speed; they are version-busted or stable.
  e.respondWith(
    caches.match(e.request, {ignoreSearch:true}).then(function(hit){
      if(hit) return hit;
      return fetch(e.request).then(function(net){
        try{ var copy=net.clone(); caches.open(CACHE).then(function(c){ c.put(e.request, copy); }); }catch(err){}
        return net;
      }).catch(function(){
        return new Response("", {status:504, statusText:"offline"});
      });
    })
  );
});
